/* Generated By:JavaCC: Do not edit this line. DbDateParserConstants.java */
package com.asksunny.dbdate;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DbDateParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AM = 1;
  /** RegularExpression Id. */
  int PM = 2;
  /** RegularExpression Id. */
  int YEAR_YY = 3;
  /** RegularExpression Id. */
  int YEAR_YYYY = 4;
  /** RegularExpression Id. */
  int MONTH_MON = 5;
  /** RegularExpression Id. */
  int MONTH_MONTH = 6;
  /** RegularExpression Id. */
  int MON_OR_MIN = 7;
  /** RegularExpression Id. */
  int DAY = 8;
  /** RegularExpression Id. */
  int HOUR = 9;
  /** RegularExpression Id. */
  int MIN = 10;
  /** RegularExpression Id. */
  int SECOND = 11;
  /** RegularExpression Id. */
  int MILLISECOND = 12;
  /** RegularExpression Id. */
  int HYPHEN = 13;
  /** RegularExpression Id. */
  int UNDERSCORE = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int SPACE = 16;
  /** RegularExpression Id. */
  int SLASH = 17;
  /** RegularExpression Id. */
  int COLON = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"AM\"",
    "\"PM\"",
    "\"YY\"",
    "\"YYYY\"",
    "\"MON\"",
    "\"MONTH\"",
    "\"MM\"",
    "\"DD\"",
    "\"HH\"",
    "\"MI\"",
    "\"SS\"",
    "\"MMM\"",
    "\"-\"",
    "\"_\"",
    "\",\"",
    "\" \"",
    "\"/\"",
    "\":\"",
  };

}
