package com.asksunny.validator;

public enum ValidationOperator {

	NONE, EQUALS, NOT_EQUALS, WITHIN, NOT_WITHIN, BETWEEN, NOT_BETWEEN, GREATER, GREATER_OR_EQUALS, LESS_OR_EQUALS, LESS, 
	
	REGEX_MATCH, REGEX_NOT_MATCH, REGEX_CONTAINS, REGEX_NOT_CONTAINS, JAVA_BEAN
}
